### ISSUE TITLE
Separate yamf-hash into own crate?

### ISSUE THREAD

**Issue by adzialocha** [pietgeursen/bamboo-rs#18]
`yamf-hash` follows its own separate [specification](https://github.com/AljoschaMeyer/yamf-hash) and might be extended in the future (ongoing discussion here: https://github.com/AljoschaMeyer/bamboo/issues/6). It is an interesting design choice as we can introduce new hashing algorithms without breaking bamboo.

To reflect the nature of `yamf-hash` I suggest separating the code from the bamboo one and give it its own crate?

**Comment by pietgeursen** [comment]
Yes! This has been on my todo list for ages and agree it should happen.
I'll add it as a thing to do before releasing 1.0 just so that I do actually to it.
