### ISSUE TITLE
publish requires full backlink and lipmaalink bytes instead of hashes

### ISSUE THREAD

**Issue by adzialocha** [pietgeursen/bamboo-rs#19]
[publish](https://github.com/pietgeursen/bamboo-rs/blob/master/bamboo-core/src/entry/publish.rs) requires the entry bytes of the backlink and lipmaalink, while the specification only mentions hashes for encoding new entries.

Changing the method to accept only hashes would not allow for checking if the right `log_id` have been used, also it wouldn't check if we falsly try to append to an ended log, but this can also be covered by the `verify` methods.

Similar to https://github.com/pietgeursen/bamboo-rs/issues/17 I'm not sure if `publish` is designed to be an already opinionated method built on top of the more low-level and generic methods, if yes, then we can close this issue!

**Comment by pietgeursen** [comment]
> Changing the method to accept only hashes would not allow for checking if the right log_id have been used, also it wouldn't check if we falsly try to append to an ended log, but this can also be covered by the verify methods.

This is reason enough to keep it as is IMHO. I want to make it hard / impossible to publish invalid messages.

I think I'm going to close this issue. But thanks for opening it. :smile:
