### ISSUE TITLE
What should this crate be named?

### ISSUE THREAD

**Issue by pietgeursen** [pietgeursen/bamboo-rs#9]
https://docs.rs/bamboo/0.0.0/bamboo/ is reserved for future use. Not sure if that's official or someone name squatting.

bamboo-rs?
bamboo-logs?
bamboo-hash-chains?
bamboo-chains?

**Comment by adzialocha** [comment]
+1 for `bamboo-rs`, simple, idiomatic and beautiful! :smile_cat:
